# Generated by Django 3.1.5 on 2021-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email2',
            field=models.EmailField(max_length=254, verbose_name='ایمل2'),
        ),
    ]
