version: "3.9"

services:
  web:
    build: .
    container_name: my_weblog
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myweblog.settings
      - PYTHONUNBUFFERED=1
