# Generated by Django 3.1.5 on 2021-01-07 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
                ('status', models.CharField(choices=[('d', 'پیشنویس'), ('p', 'منتشرشده')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('more', models.TextField(default='', verbose_name='توضیحات بیشتر')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('uni', models.CharField(max_length=200, verbose_name='دانشگاه')),
                ('comp', models.CharField(default='دانشجو', max_length=200, verbose_name='شغل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمل')),
                ('insta', models.CharField(max_length=200, verbose_name='لینک اینستاگرام')),
                ('github', models.CharField(max_length=200, verbose_name='لینک گیتهاب')),
                ('wat', models.CharField(max_length=200, verbose_name='لینک واتساپ')),
                ('tel', models.CharField(max_length=200, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'سازنده',
                'verbose_name_plural': 'سازنده ها',
            },
        ),
    ]
