# Generated by Django 3.1.5 on 2021-01-08 13:08

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to=myblog.models.upload_image_path, verbose_name='عکس'),
        ),
    ]
