# Generated by Django 3.1.5 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210118_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='آیا مقاله ی ویژه باشد؟'),
        ),
    ]
