# Generated by Django 3.1.5 on 2021-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='myblog.Category', verbose_name='دسته بندی'),
        ),
    ]
