# Generated by Django 3.1.5 on 2021-01-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
    ]
